### ISSUE TITLE
[BUG]账户余额不匹配

### ISSUE THREAD

**Issue by LeiDuang** [hass-box/state-grid#1]
今天首次安装发现账户余额与app不符合，其它数据看起来一致，等待下个周期看下数据是否能同步
![Snipaste_2024-05-12_00-13-24](https://github.com/hass-box/state-grid/assets/47079340/3a0dc618-a5ee-4c15-9a5a-5c7b7701957a)
![Snipaste_2024-05-12_00-13-33](https://github.com/hass-box/state-grid/assets/47079340/c29ed7cb-ee1d-415b-a947-86c2a0700641)

**Comment by EastWoodYang** [comment]
建议升级看看
