### ISSUE TITLE
【年度累计用电】【账户余额】取值问题

### ISSUE THREAD

**Issue by SeanChengN** [hass-box/state-grid#10]
数据读取自 state_grid.config 文件，
如下图【年度累计用电】应该为 “5258”
![chrome_c9QdJDzv5S](https://github.com/user-attachments/assets/4bf33b18-bca7-42c3-a7f7-1c37c3efe2fd)
![chrome_WuHUoEVWwc](https://github.com/user-attachments/assets/698db45b-cdda-4c79-bb69-e4382db29254)

如下图【账户余额】应该为 “205.67”
![chrome_srcBqb7OPG](https://github.com/user-attachments/assets/88592ebd-169b-4bd3-b49a-96b1a23ffbf5)
![chrome_kOby5C4BiG](https://github.com/user-attachments/assets/1b9caddd-b39b-4487-9f30-3c64490cc9a1)

**Comment by EastWoodYang** [comment]
好的，后续修复
