### ISSUE TITLE
通过命令加载报失败

### ISSUE THREAD

**Issue by KleinPan** [hass-box/state-grid#3]
通过SSH或Terminal & SSH加载项执行一键安装命令报错
curl: (22) The requested URL returned error: 404

**Comment by EastWoodYang** [comment]
请重试

**Comment by KleinPan** [comment]
重试了四五次了，其他人都是好的吗？

**Comment by PSC-F** [comment]
> 重试了四五次了，其他人都是好的吗？ 
不行404，oss的链接有问题，手动安装在12.3os下无法登陆

**Comment by EastWoodYang** [comment]
请通过集成商店安装

**Comment by ZHonry** [comment]
> 请通过集成商店安装

<img width="1117" alt="iShot_2024-06-07_19 18 03" src="https://github.com/hass-box/state-grid/assets/22869840/19f6cede-9ceb-420e-bf7c-80bcc3dc3d8c">
<img width="393" alt="iShot_2024-06-07_19 17 42" src="https://github.com/hass-box/state-grid/assets/22869840/c39744fc-3950-4cc7-a7fd-681f3b8534eb">
