### ISSUE TITLE
能源配置，用电量绑定电网的日总用电量，提示“以下实体没有预期的设备类别”

### ISSUE THREAD

**Issue by JusKyle** [hass-box/state-grid#6]
![image](https://github.com/hass-box/state-grid/assets/36150985/2055004c-07c3-4199-b8c1-1cb510e31ca9)
请教大佬，如何修改才能让能源配置不报错

**Comment by EastWoodYang** [comment]
为兼容更多的HA版本，新版本删除了该实例值类型。另外不建议添加到能源配置中。
