### ISSUE TITLE
关于token失效更新

### ISSUE THREAD

**Issue by chenjiezb** [hass-box/state-grid#7]
感谢大佬制作的这个HA集成，目前使用中发现此集成无法自动更新token，只能在失效后手动重新登录获取新token。
有时提醒滞后，或忘记手动登录，会导致日总用电量等实体无法按时获取新数据，造成历史数据缺失。
我们可以在token失效前通过自动化发出通知提醒，但无法在token失效前主动重新登录，大佬是否考虑优化下功能，以实现在token失效前，允许在集成配置里重新登录，避免上述问题出现？

**Comment by EastWoodYang** [comment]
可以考虑下调整下轮训间隔，我至今未遇到 token 失效。
也可结合通知提醒手动重新登录

**Comment by chenjiezb** [comment]
谢谢！
还有，token失效是否与在APP或小程序上登录有关？我想起来近期登录过

**Comment by EastWoodYang** [comment]
web 登录会影响 token 刷新，App 好像不会，小程序还不清楚，你可以试试

**Comment by liujhjack** [comment]
> 可以考虑下调整下轮训间隔，我至今未遇到 token 失效。 也可结合通知提醒手动重新登录

请问下大佬的轮询间隔设置的多久，我设置的12小时，会失效

**Comment by EastWoodYang** [comment]
> 请问下大佬的轮询间隔设置的多久，我设置的12小时，会失效

我设置为1小时

**Comment by norikohxb** [comment]
昨天升级了HA的内核还有重启了几次，今天国家电网就不可用了，也没有提示要重新用app扫码来登陆。请问其他人有没有相同问题？

**Comment by li988216** [comment]
手动更新至0.1.2问题解决@norikohxb
